from flask import Flask, send_file, request, jsonify
import settings
from threading import Thread
import demo_flask as wcrun
from rwini import *
import time
import os
import base64
import io

ip = settings.ip
port = settings.port

app = Flask(__name__)

def async_qwq(f):
    def task_qwq(*args, **kwargs):
        t = Thread(target=f, args=args, kwargs=kwargs)
        t.start()
    return(task_qwq)

@async_qwq
def gene(groupid, groupname, bg, bgtext, pkey:str):
    gstat = 读配置项("stat.ini", "wcstat", str(groupid) + pkey, 空项返回 = '0')
    if(gstat != '1'): #不在处理队列,开始处理
        写配置项("stat.ini", "wcstat", str(groupid) + pkey, '1') #1-处理中 0-未处理或护理完成
        wcrun.out(int(groupid), groupname, bg, bgtext, pkey)
    else: #已在处理队列
        pass

@async_qwq
def jsongene(bg, jsonlist:list, pkey:str):
    gstat = 读配置项("stat.ini", "wcstat", pkey, 空项返回 = '0')
    if(gstat != '1'): #不在处理队列,开始处理
        写配置项("stat.ini", "wcstat", pkey, '1') #1-处理中 0-未处理或护理完成
        wcrun.jsonout(bg, jsonlist, pkey)
    else: #已在处理队列
        pass

@app.route('/wordcloud', methods=["GET"])
def req():
    groupid = request.args.get("id")
    groupname = request.args.get("name")
    bg = request.args.get("bg")
    bgtext = request.args.get("text")
    pkey = request.args.get("key")
    

    if(pkey not in settings.keys):
        return(jsonify({'stat': 500, 'msg': "Invalid key", 'file': ''}), 403)
    if(pkey == None):
        pkey = ''

    if(bg == None):
        bg = "chieri_mask"

    if(os.path.isfile("./Images/" + bg + ".png") == False):
        return(jsonify({'stat': 500, 'msg': "Invalid parameter `bg`", 'file': ''}), 500)

    if(bgtext == None):
        bgtext = "Generated By Chieri Bot"

    ts = int(读配置项("stat.ini", "wctime", str(groupid) + pkey, 空项返回 = '0'))
    time_now = int(time.time()) #10位时间戳(s)

    if(ts + settings.cold > time_now): #冷却
        if(os.path.isfile("./Images/" + groupid + pkey + ".jpg") == True):

            return(jsonify({'stat': 200, 'msg': 读配置项("stat.ini", "wcstat", groupid + pkey, "") + '下次缓存刷新时间:' + str(ts + settings.cold - time_now) + '秒', 'file': settings.host + '/getwcimg?id=' + groupid + pkey}), 200)
        else:
            return(jsonify({'stat': 500, 'msg': 读配置项("stat.ini", "wcstat", groupid + pkey, "未知错误") + ' ' + '下次缓存刷新时间:' + str(ts + settings.cold - time_now) + '秒', 'file': ''}), 500)

    else:
        gene(groupid, groupname, bg, bgtext, pkey)
        return(jsonify({'stat': 202, 'msg': 'building', 'file': ''}), 202)

    return(groupid + groupname)

@app.route('/jsoncloud', methods=["POST"])
def reqwq():
    bg = request.args.get("bg")
    pkey = request.args.get("key")
    
    jsonlist = request.json

    if(pkey not in settings.keys):
        return(jsonify({'stat': 500, 'msg': "Invalid key", 'file': ''}), 403)

    if(jsonlist == None):
        return(jsonify({'stat': 500, 'msg': "Invalid post body", 'file': ''}), 500)

    if(bg == None):
        bg = "chieri_mask"

    if(os.path.isfile("./Images/" + bg + ".png") == False):
        return(jsonify({'stat': 500, 'msg': "Invalid parameter `bg`", 'file': ''}), 500)

    ts = int(读配置项("stat.ini", "wctime", pkey, 空项返回 = '0'))
    time_now = int(time.time()) #10位时间戳(s)

    if(ts + settings.jcold > time_now): #冷却
        if(os.path.isfile("./Images/" + pkey + ".png") == True):

            return(jsonify({'stat': 200, 'msg': 读配置项("stat.ini", "wcstat", pkey, "") + '下次缓存刷新时间:' + str(ts + settings.jcold - time_now) + '秒', 'file': settings.host + '/getwcimg?id=' + pkey}), 200)
        else:
            return(jsonify({'stat': 500, 'msg': 读配置项("stat.ini", "wcstat", pkey, "未知错误") + ' ' + '下次缓存刷新时间:' + str(ts + settings.jcold - time_now) + '秒', 'file': ''}), 500)

    else:
        jsongene(bg, jsonlist, pkey)
        return(jsonify({'stat': 202, 'msg': 'building', 'file': ''}), 202)

    return(groupid + groupname)

@app.route('/getwcimg')
def qwq():
    groupid = request.args.get("id")
    if(os.path.isfile("./Images/" + groupid + ".jpg") == True):
        with open("./Images/" + groupid + ".jpg", 'rb') as bites:
            return send_file(
                io.BytesIO(bites.read()),
                mimetype='image/jpg'
            )
    elif(os.path.isfile("./Images/" + groupid + ".png") == True):
        with open("./Images/" + groupid + ".png", 'rb') as bites:
            return send_file(
                io.BytesIO(bites.read()),
                mimetype='image/png'
            )
    else:
        return(jsonify({'stat': 500, 'msg': 'img error', 'file': ''}), 404)

if __name__ == '__main__':                        #正式部署请使用下面的代码
    app.run(ip, port ,debug=True) 
#if __name__ == "__main__":
#    from waitress import serve
#    serve(app, host=ip,port=port)